# Theory

This is a list of theories that typically used in social science.

## Hofstede's cultural dimensions theory


## Social Comparison

Opower used social comparison to reduce energy use around the worlds. It's not about scientific facts, or research. It's about your position relative to others (i.e., whether you are better or worse at conserving energy compared to your neighbors) [@Cuddy_2010]

## Power Distance Theory



## Distraction Conflict Theory


## Optimal Distinctiveness Theory 


Even though the previous study argued that either assimilation (communicate social identity) or differentiation (uniqueness motive) could prevail in any consumer decision [@Mason_2007].  

[@Chan_2012] find that consumers can have both mechanisms satisfied when making a purchase decisions   

People conform under the informational or normative influence [@Deutsch_1955]. People also make choices and decision similar to their aspiration groups to signal their desired identities [@Berger_2007; @Englis_1995].  

People also have intricate needs for uniqueness [@Lynn2002], since people sometimes experience an emotional reaction when being too similar. Unique motives can be driven by situational factors.  

"consumers simultaneously pursue assimilation and differentiation goals on different dimensions of a single choice: they assimilate to their group on one dimension (by conforming on identity signaling attributes such as brand) while differentiating on another dimension(distinguishing themselves on uniqueness attributes such as color). Desires to communicate social identity lead consumers to conform on choice dimensions that are strongly associated with their group, particularly in identity-relevant consumer categories such as clothing. Higher needs for uniqueness lead consumers to differentiate within groups by choosing less popular options among those that are associated with their group" [@Chan_2012]  

From the optimal distinctiveness theory, people seek to satisfy both the need fo assimilation nd differentiation (Brewer, 1991)
“consumption gains symbolic meaning as a marker of group membership” [@Chan_2012]  

The consumer can simultaneously assimilate (i.e., by conforming to reference groups by choosing attribute that signals group identity such as brand) while differentiating from other in-group members on other choice dimensions such as color to achieve optimally distinct self-concept [@Chan_2012].  


People diverge from members of other social groups (dissimilar outgroups): when other social groups adopt tastes, people might abandon their current tastes to avoid signaling undesired identities, and costs of misidentification [@Berger_2007]  



## Social Exchange Theory

## Resource Dependence Theory   

External resources (or the procurement of external resources) of organizations can influence the organization's behavior [@Stern_1979]

The basic premise is as follows:   

Organizations depend on resources, which depends on its environment, where other organizations play a big part to operate (ecology). And resources are power, and one organizations need others to survive. Hence, power and resource dependence are interlocked.  

Since an organization's power (A) over another (B) is the same thing as organization B's dependence on organization A. We can see that power is relational and situaitonal. 


## Resource based Theory

Also known as resource-based view (RBV) 

[@Wernerfelt_1984] was the first seminal paper on RBV. Later on, [@Barney_2011] argued for RBV to be considered a theory. 

### Assumptions 

1. Resource heterogeneity assumption  

Firms have different bundles of resources [@Peteraf_2003]. Hence, firms are skilled at certain activities due to their unique resources. 

2. Resource immobility assumption  

Differences in resources can be sustained due to the difficulty in trading resources. 


Based on these two assumption, [RBT][Resource based Theory] argues that since other firms find these valuable resources too costly or too difficult to imitate, then firms having these resources can have **sustainable competitive advantage** (SCA) [@Barney_2012]

Since not all resources are drivers of SCA, only resources are "simultaneously valuable, rare, imperfectly imitable, and exploitable by the firm’s organization". (based on VIRO) [@Kozlenkova_2013]

### VIRO
#### Valuable
Firm resources are valuable if they “enable a firm to develop and implement strategies that have the effect of lowering a firm’s net costs and/or increase a firm’s net revenues beyond what would have been the case” without these resources [@Barney_2017]

## Assumptions and logic





## Network Exchange Theory 
Cook and Whitmeyer 1992
Markovsky, Willer, Patton 1998 


## Signaling Theory 
When do we diverge? When choices signal identity (observability, functional benefits, etc.)  

People diverge to signal identity, which based on:  

 * Observability  
 * Functional benefits
 
"The more costly something is, the more likely it is to retain its value as a clear and accurate signal." [@Berger_2016]
Costs in this case could be:  

 * Monetary 
 * Opportunity 
 * Time 
 
Price and branding (brand prominence) has an inverted-U relationship
The higher the price is, the more brand prominence it possess. 
However, for the ultra rich class, the highest price does not command highest brand prominence, but actually lowest brand prominence. (a small set of ultra rich people know)


"The identity-signaling drives things to both catch on and die out... Counterfeiting helps speed up the process "  

Counterfeit and piracy are good because it keeps consumers crave for a new one [@Berger_2016]


We know that the mere exposure can increase our preference towards an object. Interestingly, the similarity between a new object and one that we are familiarity with also have the same effect. Novel but don't be too novel. 




## Goal Gradient Hypothesis

How close you are to achieve a bonus with your loyalty card, the more motivated you are. Compared to beginner coffee buyers, customers who almost complete a card buy more coffee (come back to the store sooner) [@Kivetz_2006]

Similar effects are also found in animals, rats are more motivated when they are closer to their goals [@Brown_1948;@Hull_1932;@Hull_1934]


However, too far behind couples with direct competition could not only lead people a little behind more motivated, but people far behind more demotivated. [@Fershtman_2011]

Interestingly, the mechanism for favored candidate to lose motivation is different from underdogs. To save face, favored candidate stops trying to have reason to excuse that if they were to keep trying, they would have won [@Dai_2018]


## Adaptation Theory of Well-being
[@Diener_2006] People tend to return to their previous level of happiness after traumatic events. we tend to stay in a long-term disposition. 

[@Lyubomirsky_2005] long-term happiness depends 50% on a person's genetic set point, 10% on circumstances (whether you, how rich, how healthy they are), and 40% on what they choose to think and do. Hence, even if our friends are happy, they happiness will wear off, and return us the original level. 


## Discrepancy-attribution hypothesis 


## The broaden-and-build theory of positive emotions 

## Regulatory Focus Theory 

According to self-regulatory focus, people have either promotion focus (presence of desirable outcomes) or prevention focus (absence of undesirable outcomes). Promotion focus people tend to focus on growth, aspirations, achievement, while presentation focus people have an orientation towards safety or vigilance [@Lee_2004]. Hence, advertisers (promotion-focused or prevention-focused) can create messages depend on their audience  [@Aaker_2001]. Regulatory focus can depend on culture (western is more promotion focus as compared to eastern more prevention focus [@Lee_2000]), products (home-security or massage chairs), environment (e.g., 2000 bubble bursts induce investors to be more prevention-focused). 



