---
output:
  pdf_document: default
  html_document: default
---
# Effect

This chapter is dedicated to well-known effects that explain interesting phenomenon. 

## Coolidge Effect
This effect comes from the biological world, where male mammals renew their sexual interest when a new female is introduced even though the males have shown exhaustion from encounters with the previous partners. Interestingly, females exhibit this effect to a lesser extent.  

The name Coolidge comes from a joke about President Calvin Coolidge. The story is as follow:  
"... The President and Mrs. Coolidge were being shown (separately) around an experimental government farm. When [Mrs. Coolidge] came to the chicken yard she noticed that a rooster was mating very frequently. She asked the attendant how often that happened and was told, "Dozens of times each day." Mrs. Coolidge said, "Tell that to the President when he comes by." Upon being told, the President asked, "Same hen every time?" The reply was, "Oh, no, Mr. President, a different hen every time." President: "Tell that to Mrs. Coolidge." [@Johnson_1972]  

## Social Facilitation / Inhibition

This phenomenon happens when the mere presence of others can alter ones' performance.  
When the presence of others improve one's performance, we term it social facilitation.
When the presence of others impair one's performance, we term it social inhibition.

The phenomenon was first documented by [@Triplett_1898]. And later [@Allport_1920] labeled it as social facilitation

The moderator that decides whether the process is social facilitation or social inhibition is task familiarity/ complexity. The more familiar one is with a task, social facilitation will occur. The more difficult or novel a task is, the more likely that social inhibition will occur. According to [@Zajonc_1966], "an audience impairs the acquisition of new responses and facilitates the emission of well-learned responses" (dominant responses). Hence, when facing a difficult task in combination with the presence of others will result in high arousal which results in stress and poor performance. 

The mechanism can be specified by the [Distraction Conflict Theory], which states that the conflict between giving attention to spectators and to a task affects performance. Better performers resolve this conflict and direct more attention to the task.

Another mechanism claim that it's not the presence of others that affects performance, but the knowledge of others' evaluation affect performance. Performers are aroused by audiences because they know that the are being evaluated. Hence, technically, passive spectators are not that "passive". [@Cottrell_1968]. This attempt to appear better in others' eyes is also known as impression management, which has been studied extensively in management.


|Social Presence | Task | Consequence|
|---|---|---|
|Presence of others |Automatic, natural, well-learned|Social Facilitation|
||Difficult requires more attention|Social Inhibition|


There are two stream of research which are   

 * [Audience Effect]  
 * [Coaction Effect]  

### Audience Effect
Passive spectators affects performance
Notable articles are:  

 * increased multiplication performance [@Travis_1925]
 * decreased memorizing a list of nonsense words [@Pessin_1933]

### Coaction Effect
Active participants (same activity separately)affect performance 
The effect was also documented in animals such as  

 * ants will dig three times more with the presence of other ants  [@Chen_1937]
 * animals will eat more with the presence of other of their species  [@Platt_1967]
 
 
## Snob Effect
This is effect is from micro-economics in which people demand for goods or services is negatively correlated with the market demand.  [@Leibenstein_1950]
In the market of unique, expensive, or unusual products, price can be seen as quality itself. These items typically have high economic value (status) but low practical value. The availability of a product is negatively correlated with it snob value. 

Examples are arts, designer clothes.  

Snob effects are when an individual's demand for goods or services is negatively correlated with market demand. One might avoid buying things or doing things when too many are doing them (like a badge of distinction). To combat this, we can employ an illusion of distinction. Hence we focus on ways things are different, even if at the core they are very much the same. 


## Warm Glow Heuristic
"The positive valence of a stimulus increases its perceived familiarity, even in the absence of prior exposure." [@Monin_2003]
Familiarity leads to liking because the ease of retrieving information in our brain. This mechanism also has evolutionary benefits, which helps familiarity stay together (spouses, children, parents). 
We know that familiarity leads to liking (preference), but the the other way around also works.  

Working-class people prefer similarity, and high-end people prefer uniqueness [@Berger_2016]

Similarity increases evaluation (and sales) for the same reason that mere exposure works. It is easy for our brain to process information (associative network) [@Berger_2016]  

So is that people like to be familiar [Warm Glow Heuristic], or to be novel [Coolidge Effect]? The answer is both: [Goldilocks Effect] or the middle ground.

## Goldilocks Effect
"just the right amount" - U-shaped relationship. Beth Hess and Joan M.Waring introduced the term to refer to the optimal level of contact with kin that satisfies married couples. [@Spanier_1978]   

Relatively complex things may take longer to learn but also have a longer-lasting appeal. Affective reactions often follow a Goldilocks effect or interviewed U-shape trajectory.   

Too novel, and it is unfamiliar. Too familiar, and it's boring; the middle is just right. [@Berger_2016]  

Moderately discrepant thing s tend to garner more attention [@McCall_1977]  

One way to encourage perseverance is to shrink the comparison set, breaking larger groups into smaller ones based on performance  

Affection reactions operate under this mechanism. Too novel products make use feel unease (or neutral) because we are unfamiliar. But the things that we interact too many times bored us. However, the right amount of interaction will hold our affection reaction at the optimal level.

Complexity also works on the same scale. Simple things can have us quickly attracted to, but we will get bored of it quickly. 
Complex things will take long time to learn. But once we get accustomed to it, it's hard to get rid of a habit.


## Glass Cliff Effect 

This effect is when women are more likely to be appointed to a more challenging position (poorly performing orgs), while men are like more likely to be appointed to a stable leadership position [@Ryan_2005;@Ryan_2016]. The term was first coined by Michelle K. Ryan and Alexander Haslam, who studied FTSE 100. Later on, another study also found the effect in law students who were assigned more difficult cases.

Possible explanations: 

 (1) Struggling companies can easily blame someone if she fails to pull the company out of trouble. Moreover, even if the company fails, they can still be labeled progressive.


**Note**  
This effect also applies to minorities or any marginalized groups.


